- src/Scanner/PropertyScanner.php
- test/Scanner/PropertyScannerTest.php
Example:
```php
<?php
$source = <<<'EOS'
<?php
class Pizza
{
public $price = 100;
}
EOS;
$scanner = new Zend\Code\Scanner\TokenArrayScanner(token_get_all($source));
$class   = $scanner->getClass('Pizza');
$price   = $class->getProperty('price');
var_dump($price->getValueType()); // => NULL
```
If other method was called at first:
```php
$scanner = new Zend\Code\Scanner\TokenArrayScanner(token_get_all($source));
$class   = $scanner->getClass('Pizza');
$price   = $class->getProperty('price');
var_dump($price->getValue());     // => string(3) "100"
var_dump($price->getValueType()); // => string(3) "int"
```
> Fix bug -- return null when `getValueType()` is called at first.

- composer.json
- src/Annotation/AnnotationManager.php
- test/Annotation/AnnotationManagerTest.php
This PR contains the code refactor using the new zend-eventmanager of ZF3.
> Code refactor with new zend-eventmanager

- src/Generator/ValueGenerator.php
- test/Generator/ValueGeneratorTest.php
Alternative to  #22.
Note: PropertyReflection require stdlib PriorityQueue due the EventManager use.
Close: #22
Fix: #21
> Make Stdlib's ArrayObject a soft dependency of ValueGenerator

- src/Generator/ValueGenerator.php
- test/Generator/ValueGeneratorTest.php
Added the creation of shorty syntax arrays.
This is the new behaviour:
```
$expectedSource = <<<EOS
[
'foo',
]
EOS;
$valueGenerator = new ValueGenerator();
$valueGenerator->setValue(['foo']);
$valueGenerator->setType(ValueGenerator::TYPE_ARRAY_SHORT);
var_dump($expectedSource === $valueGenerator->generate()); /// Outputs true
```
The old behaviour still works as expected and is the default behaviour:
```
$expectedSource = <<<EOS
array(
'foo',
)
EOS;
$valueGenerator = new ValueGenerator();
$valueGenerator->setValue(['foo']);
var_dump($expectedSource === $valueGenerator->generate()); /// Outputs true
```
Should fix issue #9
> Added the creation of array with short syntax

- composer.json
Installing the full doctrine/common package is not necessary when only doctrine/annotations is used
> Use a bound constraint and right package for the doctrine annotations

- .travis.yml
- CHANGELOG.md
- composer.json
This patch updates the 2.6 series to allow using zend-stdlib 2.7 **or** 3.0 releases. The only functionality used from zend-stdlib is the `ArrayObject` implementation, which maintains compatibility across versions.
> Updated dependencies to allow stdlib v3

- composer.json
- src/Scanner/ClassScanner.php
- src/Scanner/DocBlockScanner.php
Updated to allow either 2.7 or 3.0 releases, as the functionality used does not change API between versions.
This also updates the PHP constraint to disallow PHP 7.0.5, fixing #49.
> Updated stdlib requirement

- phpcs.xml.dist
- src/Generator/MethodGenerator.php
- src/Reflection/DocBlock/Tag/AuthorTag.php
- src/Reflection/DocBlock/Tag/GenericTag.php
- src/Reflection/DocBlock/Tag/LicenseTag.php
- src/Reflection/DocBlock/Tag/MethodTag.php
- src/Reflection/DocBlock/Tag/PropertyTag.php
- src/Reflection/DocBlockReflection.php
- test/Generator/TestAsset/TestClassWithManyProperties.php
- test/Reflection/DocBlockReflectionTest.php
- test/Reflection/ReflectionDocBlockTagTest.php
- test/Scanner/TestAsset/MapperExample/Mapper.php
- test/Scanner/TestAsset/MapperExample/RepositoryA.php
Uniformazing the line ending in the project to avoid issue
with windows.
Fix #45 and Fix #39
> Trying to fix a platform issue with windows line ending

- .gitignore
- .travis.yml
- doc/book/generator/examples.md
- doc/book/generator/reference.md
- doc/book/index.html
- doc/book/migration.md
- doc/bookdown.json
- mkdocs.yml
- Removed bookdown artifacts
- Simplified several headings that were breaking the ToC
- Updated doc examples to use short array notation
- Created proper mkdocs dicts for the ToC
- Added docs landing page
- Added travis integration
> Created documentation build automation

- src/Scanner/MethodScanner.php
- test/Scanner/ClassScannerTest.php
- test/Scanner/MethodScannerTest.php
- test/TestAsset/BarClass.php
Previously, `MethodScanner` did not detect a leading `T_NS_SEPARATOR`
character for a type name. By failing to detect it, it passes it to
`ParameterScanner` without it, who then dutifully resolves the classname
as if it was relative to the current namespace.
This is obviously incorrect behaviour, and it is fixed with this patch.
Tests have also been added and updated.
> Fix handling of FQCNs in method parameters

- src/Generator/ClassGenerator.php
- test/Generator/ClassGeneratorTest.php
This PR fixes #64. It will try to look for the classnames in the use statements and will validate if the classes live in the same namespace as the class that is being generated.
If this is the case, the short classname is being used instead of the full classname.
If this is not the case, the backslash is added to make sure that the classes can be loaded by PHP.
> Use correct class names in the ClassGenerator implements and extend.

- src/Scanner/TokenArrayScanner.php
- test/Reflection/FileReflectionTest.php
- test/Reflection/TestAsset/issue-70.php
- Added a failing test case, per #70.
- Discovered that the structure addressed can be either an array (existing assumption) or a string.
- Updated the assignment to check for array before assigning, and use the string value if present instead.
Fixes #70.
Fixes #43.
> Provide a fix for issue #70

- src/Scanner/ClassScanner.php
- test/Scanner/ClassScannerTest.php
- test/TestAsset/BazTrait.php
- Only the first use statement would be accounted for when getting lists
of traits, due to unnecessary break statements at the end of the loop.
Fixes #58
- If one of the methods touched by this commit, such as getTraitNames(),
or getTraits(), which calls getTraitNames(), was called as the first
action on this class, no traits would be returned, due to the fact
that scan() was not called at the start of the method. Fixes #57
> Resolve issues with traits in ClassScanner

- src/Scanner/ClassScanner.php
- test/Scanner/ClassScannerTest.php
1. Fix ClassScanner::getInterfaces() which don't work with Interface.
2. add TestCase  ClassScannerTest::testGetInterfacesFromInterface().
from issue https://github.com/zendframework/zend-code/issues/90
> 1. Fix ClassScanner::getInterfaces() which don't work with Interface.

- src/Generator/ParameterGenerator.php
- test/Generator/ParameterGeneratorTest.php
- test/Generator/TestAsset/ParameterClass.php
Consider the following example:
```php
class Foo {
public function doSomething(\stdClass $a = null, $b) {
}
}
```
By generating a method from the ReflectionMethod of the given code above, the generated code did not consider the default value from $a. This has the effect, that one cannot pass null into that variable any more.
This PR fixes this. See also Ocramius/ProxyManager#337
> Fix generation of non-optional object parameters that can be null.

- src/Generator/TypeGenerator.php
It is currently called twice with the same argument.
> Don't call isInternalPhpType() twice in TypeGenerator

- test/Generator/ClassGeneratorTest.php
- test/Generator/TraitGeneratorTest.php
- test/Reflection/ReflectionDocBlockTagTest.php
In assertions we should have as the first param "expected value" and as the second "actual".
In some places we have it incorrectly.
> Fixes in tests - changed order of params

- .travis.yml
This channel is no longer supported.
> Remove IRC notifications in travis configuration

- src/Generator/ParameterGenerator.php
- src/Generator/PropertyGenerator.php
- src/Generator/ValueGenerator.php
- test/Generator/ParameterGeneratorTest.php
- test/Generator/PropertyGeneratorTest.php
> Add omit property value type

- src/Generator/ParameterGenerator.php
The setter always transforms any value to a ValueGenerator. Extended classes that manually set `$this->defaultValue` could experiece a behavior change. But to me it looks like an unintended code paths as the it is not documented what happens with int, float, bool etc. And it breaks for array for example.
> Default value of ParameterGenerator is always a ValueGenerator

- src/Generator/MethodGenerator.php
- test/Generator/ClassGeneratorTest.php
- test/Generator/FileGeneratorTest.php
- test/Generator/MethodGeneratorTest.php
- test/Generator/TestAsset/TestSampleSingleClass.php
Adds a `Zend\Code\Generator\MethodGenerator::copyMethodSignature` method that is similar to `fromReflection()` but without the copying the method body and phpdoc as this is quite heavy to parse (it requires file IO, regexes, tokenization of code).
It's for example useful when creating proxies where you normally change the method body afterwards anyway. See https://github.com/Ocramius/ProxyManager/pull/393 where it increases performance.
> Add MethodGenerator::copyMethodSignature without body and phpdoc

- CHANGELOG.md
It's already fixed in release notes:
https://github.com/zendframework/zend-code/releases/tag/release-3.1.0
> Fixed links to PRs in CHANGELOG

- src/Scanner/MethodScanner.php
- test/Scanner/MethodScannerTest.php
Exception - which is used as exception class within setVisibility - is not a class but a (sub)namespace. InvalidArgumentException likely is the intended exception class here.
This is my first submission. Wanted to get my feet wet with the submission workflow. :)
> Corrected the exception class used and removed unnecessary strtolower in MethodScanner::setVisibility

- src/Generator/ClassGenerator.php
- src/Generator/DocBlock/Tag/AbstractTypeableTag.php
- src/Generator/DocBlock/Tag/AuthorTag.php
- src/Generator/DocBlock/Tag/ParamTag.php
- src/Generator/DocBlockGenerator.php
- src/Reflection/ClassReflection.php
- src/Reflection/DocBlock/Tag/MethodTag.php
- src/Reflection/DocBlock/Tag/PropertyTag.php
- src/Reflection/DocBlockReflection.php
- src/Reflection/FileReflection.php
- src/Reflection/FunctionReflection.php
- src/Reflection/MethodReflection.php
- src/Reflection/ParameterReflection.php
- src/Reflection/PropertyReflection.php
- src/Scanner/MethodScanner.php
- src/Scanner/PropertyScanner.php
- src/Scanner/TokenArrayScanner.php
This PR contains docblock return type fixes. It might be a good idea to merge this, if 4.0.0 won't be released any time soon.
> Fixed docblock return types for 3.x releases

- src/Reflection/DocBlock/Tag/VarTag.php
- test/Reflection/DocBlock/Tag/VarTagTest.php
- test/Reflection/ReflectionDocBlockTagTest.php
- test/Reflection/TestAsset/TestSampleClass14.php
Var tag pattern now allows var tags without the variable name. This fixes #128.
> Fixed regex pattern in VarTag doc block reflection class

- src/Generator/FileGenerator.php
- src/Reflection/MethodReflection.php
Removes related deprecations when running with PHP 7.3.
> Replace "continue" by "break" in "switch" statements

- .travis.yml
Updated Travis CI configuration to run all tests on PHP 7.3 with lowest/locked/latest dependencies
> Added PHP 7.3 support

- src/Generator/ValueGenerator.php
- test/Generator/ValueGeneratorTest.php
PR for #163 
I was use auto generated complex arrays with personal data for tests, so I cant publish it.
> recursively set indentations for child arrays

- src/Generator/PropertyGenerator.php
- test/Generator/ClassGeneratorTest.php
- test/Generator/InterfaceGeneratorTest.php
- test/Generator/PropertyGeneratorTest.php
- test/Generator/ValueGeneratorTest.php
- test/TestAsset/BarClass.php
- test/TestAsset/FooClass.php
- test/TestAsset/FooInterface.php
As we support already only PHP 7.1+ we can define visibility for constants.
Added tests and updated current tests.
Default visibility is `public`.
> Feature: constant visibility

- src/DeclareStatement.php
- src/Declare_.php
- src/Generator/FileGenerator.php
- test/Generator/FileGeneratorTest.php
This will add the ability to configure declare() statements
at the top of generated files. 
I took the implementation suggestion from @GaryJones in #102 and changes it a bit.
I changed the behavior to be only able to generate valid `declare` statements at all.
Also I added static factories to generate the possible directives.
Should solve #102
---
~One problem tho. Since `declare` is a reserved keyword. The I decided to go with `Declare_` as the class representation. But the codesniffer doesn't like this. Any suggestions?~ Renamed to `DeclareStatement` as suggested by @webimpress
> Feature: Add ability to define declare statements

- src/Scanner/MethodScanner.php
With 7.4.0beta4
```
There were 16 errors:
1) ZendTest\Code\Scanner\ClassScannerTest::testClassScannerHasClassInformation
Trying to access array offset on value of type null
/work/GIT/zend/zend-code/src/Scanner/MethodScanner.php:455
/work/GIT/zend/zend-code/src/Scanner/MethodScanner.php:592
/work/GIT/zend/zend-code/src/Scanner/MethodScanner.php:155
/work/GIT/zend/zend-code/src/Scanner/ClassScanner.php:712
/work/GIT/zend/zend-code/test/Scanner/ClassScannerTest.php:65
2) ZendTest\Code\Scanner\ClassScannerTest::testClassScannerHasMethods
Trying to access array offset on value of type null
/work/GIT/zend/zend-code/src/Scanner/MethodScanner.php:455
/work/GIT/zend/zend-code/src/Scanner/MethodScanner.php:592
/work/GIT/zend/zend-code/src/Scanner/MethodScanner.php:155 …
```
> fix Trying to access array offset on value of type nul (7.4)

- .travis.yml
- composer.json
- composer.lock
- src/Reflection/ParameterReflection.php
- test/Reflection/ParameterReflectionTest.php
we can't cast `ReflectionType` to `string` now - we must use `->getName()`
> PHP 7.4 compatibility fixes
